#%RAML 1.0
title: salesforce-opt-api

/opportunities:
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
  get:
    responses:
      200:
        body:
          application/json:
            
                                            